### PR TITLE
Bump bitcoin sv2-tp to v0.1.9 + update imports

### LINKED ISSUE #9: Current bitcoin fork version out of date + can result in segfault
# Background
Currently, the workshop uses the [`sv2-tp-0.1.3`](https://github.com/Sjors/bitcoin/releases/tag/sv2-tp-0.1.3) tag. This was the most updated tag that worked reliably.

On 2024.08.09, @Sjors released a new [`sv2-tp-0.1.9`](https://github.com/Sjors/bitcoin/releases/tag/sv2-tp-0.1.9) tag that fixes the `0.1.5` segfault @plebhash and I encountered when playing around with the workshop.

# Problem
The workshop should be using the most recent tag.

# Solution
Update the [`Dockerfile`](https://github.com/stratum-mining/sv2-workshop/blob/bf2d39f20fc8545ecfee6489c8f1fefbd04deb0e/materials/Dockerfile#L47) to checkout the `sv2-tp-0.1.9`. Run the workshop and verify no seg fault (or other error) is encountered. Update any documentation referencing the tag.

> Note: The `sv2-tp-0.1.9` is based on the `master` of Bitcoin Core on 2024.09.03 which introduces `cmake`. This will require different packages and install commands.

### PR DESCRIPTION
**Pull request by rrybarczyk**
Addresses #9.

### CODE REVIEW

**Review by plebhash — APPROVED** [review]
utACK

**Comment by rrybarczyk** [comment]
When running with the Genesis node on the SRI VM with the version tag `sv2-tp-0.1.3`, everything seems to works nicely (although I am unable to view the mempool.space hosted on the SRI VM because I cannot run `docker-compose up` in the `mempool` directory as `docker-compose` is not installed and I do not have `sudo` privledges):

Screenshot 2024-09-17 at 11 56 00 AM

Screenshot 2024-09-17 at 11 56 43 AM

When using a local Genesis node on `sv2-tp-0.1.9`, the pool and JDS roles receives the following errors:

Screenshot 2024-09-17 at 12 36 43 PM

I am not sure if this is an issue with my local Genesis node, or if the problem runs deeper. Should we update the Genesis node on the SRI VM to be `sv2-tp-0.1.9` and try?

**Comment by plebhash** [comment]
the root cause is this: https://github.com/stratum-mining/stratum/blob/ab0ddd625706698c47d44b9b4e4f985c39be18db/roles/pool/src/lib/mining_pool/mod.rs#L786

solution is here https://github.com/stratum-mining/sv2-workshop/blob/bf2d39f20fc8545ecfee6489c8f1fefbd04deb0e/materials/signet-genesis-node.sh#L61-L65

**Comment by rrybarczyk** [comment]
Works now after I properly initialized the local Genesis node with 16 blocks.


Screenshot 2024-09-17 at 1 08 50 PM

Screenshot 2024-09-17 at 1 09 32 PM

**Pull request merged**
